function registry = fdei_algorithm_registry()
%FDEI_ALGORITHM_REGISTRY Return the project-local FDEI algorithm registry.
%   QMode selects the reference signal used by ideal binary-switch
%   reconstruction.  CRFRSas_c and CRFRSvs_c are intentionally registered as
%   passive/general-identification entries because no reliable control
%   reference definition is available in the supplied model contract.

template = struct( ...
    'Name', '', 'Variant', '', 'Aliases', {{}}, 'QMode', '', ...
    'NaturalUnit', '', 'RunSHADDDiagnostic', false, 'Description', '');
registry = repmat(template, 0, 1);

registry(end+1) = makeEntry('Passive', 'Passive', {'passive','baseline'}, ...
    'passive', '', false, 'Constant baseline damping');
registry(end+1) = makeEntry('Skyhook', 'SkyHook', {'skyhook','sky','sh'}, ...
    'vs', 'N*s/m', false, 'Skyhook velocity reference');
registry(end+1) = makeEntry('ADD', 'ADD', {'add','accelerationdriven'}, ...
    'as', 'kg', false, 'Acceleration-driven damping');
registry(end+1) = makeEntry('SHADD', 'SH_ADD', {'shadd','skyhookadd'}, ...
    'eta', 'kg', true, 'Combined Skyhook and ADD law');
registry(end+1) = makeEntry('FRS_c', 'FRS_c', {'frs_c'}, ...
    'passive', '', false, 'General impedance identification');
registry(end+1) = makeEntry('CRFRSas_c', 'CRFRSas_c', {'crfrsas_c'}, ...
    'passive', '', false, ...
    'Registered without inventing an unavailable control reference law');
registry(end+1) = makeEntry('CRFRSvs_c', 'CRFRSvs_c', {'crfrsvs_c'}, ...
    'passive', '', false, ...
    'Registered without inventing an unavailable control reference law');
end

function entry = makeEntry(name, variant, aliases, qMode, unit, diagnostic, description)
entry = struct('Name', name, 'Variant', variant, 'Aliases', {aliases}, ...
    'QMode', qMode, 'NaturalUnit', unit, ...
    'RunSHADDDiagnostic', diagnostic, 'Description', description);
end
