function handles = gui_simple_data_order(parent, handles)
%% 简化的数据顺序设置GUI模块
% 只需要指定哪个数据排第一（虚线），哪个排最后（黑色实线）
%
% 输入:
%   parent - 父容器对象
%   handles - GUI句柄结构体
%
% 输出:  
%   handles - 更新后的句柄结构体

    % 数据顺序设置面板
    orderPanel = uipanel('Parent', parent, ...
                        'Title', '📊 数据顺序设置', ...
                        'Position', [0.02, 0.02, 0.96, 0.96], ...
                        'FontSize', 10, ...
                        'FontWeight', 'bold', ...
                        'BackgroundColor', [0.98, 1.0, 0.95], ...
                        'ForegroundColor', [0.2, 0.6, 0.2]);
    
    % 说明文字
    uicontrol('Parent', orderPanel, ...
              'Style', 'text', ...
              'String', ['📝 指定绘图中的特殊数据:', newline, ...
                        '• 第一个数据: 显示为虚线', newline, ...
                        '• 最后一个数据: 显示为黑色实线', newline, ...
                        '• 其他数据: 自动颜色实线'], ...
              'Position', [15, 400, 200, 80], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 9, ...
              'ForegroundColor', [0.4, 0.4, 0.4]);
    
    % === 第一个数据设置 ===
    uicontrol('Parent', orderPanel, ...
              'Style', 'text', ...
              'String', '📈 第一个数据 (虚线):', ...
              'Position', [15, 360, 130, 20], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 9, ...
              'FontWeight', 'bold', ...
              'ForegroundColor', [0, 0.4470, 0.7410]);
    
    handles.firstDataDropdown = uicontrol('Parent', orderPanel, ...
                                         'Style', 'popupmenu', ...
                                         'String', {'(默认第1个)', '数据1', '数据2', '数据3'}, ...
                                         'Position', [150, 360, 120, 25], ...
                                         'FontSize', 9, ...
                                         'Value', 1, ...
                                         'Callback', {@onDataOrderChange, handles});
    
    % === 最后一个数据设置 ===
    uicontrol('Parent', orderPanel, ...
              'Style', 'text', ...
              'String', '🎯 最后数据 (黑色实线):', ...
              'Position', [15, 320, 130, 20], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 9, ...
              'FontWeight', 'bold', ...
              'ForegroundColor', [0, 0, 0]);
    
    handles.lastDataDropdown = uicontrol('Parent', orderPanel, ...
                                        'Style', 'popupmenu', ...
                                        'String', {'(默认最后1个)', '数据1', '数据2', '数据3'}, ...
                                        'Position', [150, 320, 120, 25], ...
                                        'FontSize', 9, ...
                                        'Value', 1, ...
                                        'Callback', {@onDataOrderChange, handles});
    
    % === 快速设置按钮 ===
    uicontrol('Parent', orderPanel, ...
              'Style', 'pushbutton', ...
              'String', '🚀 智能设置', ...
              'Position', [15, 280, 100, 25], ...
              'FontSize', 9, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.4, 0.8, 0.4], ...
              'ForegroundColor', 'white', ...
              'Callback', {@smartSetting, handles}, ...
              'TooltipString', '第1个数据设为第一个，最后1个数据设为最后一个');
    
    % === 重置按钮 ===
    uicontrol('Parent', orderPanel, ...
              'Style', 'pushbutton', ...
              'String', '🔄 重置', ...
              'Position', [125, 280, 80, 25], ...
              'FontSize', 9, ...
              'BackgroundColor', [0.9, 0.9, 0.9], ...
              'Callback', {@resetSetting, handles});
    
    % === 当前设置显示 ===
    uicontrol('Parent', orderPanel, ...
              'Style', 'text', ...
              'String', '📊 当前设置:', ...
              'Position', [15, 245, 80, 18], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 9, ...
              'FontWeight', 'bold');
    
    handles.orderStatusText = uicontrol('Parent', orderPanel, ...
                                       'Style', 'text', ...
                                       'String', '默认顺序', ...
                                       'Position', [15, 190, 200, 50], ...
                                       'HorizontalAlignment', 'left', ...
                                       'FontSize', 8, ...
                                       'ForegroundColor', [0.5, 0.5, 0.5]);
    
    % === 预览和应用按钮 ===
    uicontrol('Parent', orderPanel, ...
              'Style', 'pushbutton', ...
              'String', '👁️ 预览效果', ...
              'Position', [15, 150, 95, 30], ...
              'FontSize', 9, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.2, 0.6, 0.9], ...
              'ForegroundColor', 'white', ...
              'Callback', {@previewOrder, handles});
    
    uicontrol('Parent', orderPanel, ...
              'Style', 'pushbutton', ...
              'String', '✅ 应用设置', ...
              'Position', [120, 150, 95, 30], ...
              'FontSize', 9, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.1, 0.7, 0.1], ...
              'ForegroundColor', 'white', ...
              'Callback', {@applyOrder, handles});
    
    % === 帮助信息 ===
    help_text = ['💡 使用说明：', newline, ...
                '1. 选择要显示为虚线的数据', newline, ...
                '2. 选择要显示为黑色实线的数据', newline, ...
                '3. 其他数据将自动使用彩色实线', newline, ...
                '4. 点击应用设置保存配置'];
    
    uicontrol('Parent', orderPanel, ...
              'Style', 'text', ...
              'String', help_text, ...
              'Position', [15, 10, 200, 135], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 8, ...
              'ForegroundColor', [0.4, 0.4, 0.4]);
    
    % 初始化下拉与状态显示
    if exist('updateSimpleDataOrderDropdowns', 'file') == 2
        try
            updateSimpleDataOrderDropdowns(handles);
        catch
        end
    end
    updateOrderStatus(handles);
    
end


%% 回调函数 - 数据顺序改变
function onDataOrderChange(~, ~, handles)
    handles = get(handles.fig, 'UserData');
    updateOrderStatus(handles);
    gui_utils('addLog', handles, '数据顺序设置已更新');
end

%% 智能设置
function smartSetting(~, ~, handles)
    handles = get(handles.fig, 'UserData');
    
    if ~isfield(handles, 'data') || isempty(handles.data)
        msgbox('请先导入数据', '提示', 'warn');
        return;
    end
    
    num_datasets = length(handles.data);
    
    if num_datasets >= 2
        % 第一个数据设为第一个
        set(handles.firstDataDropdown, 'Value', 2);  % 数据1
        
        % 最后一个数据设为最后一个
        set(handles.lastDataDropdown, 'Value', num_datasets + 1);  % 最后一个数据
        
        updateOrderStatus(handles);
        gui_utils('addLog', handles, '智能设置完成');
        msgbox('智能设置完成！第1个数据设为虚线，最后1个数据设为黑色实线', '智能设置', 'help');
    else
        msgbox('至少需要2个数据集才能进行智能设置', '提示', 'warn');
    end
end

%% 重置设置
function resetSetting(~, ~, handles)
    handles = get(handles.fig, 'UserData');
    
    % 重置下拉列表为默认
    set(handles.firstDataDropdown, 'Value', 1);
    set(handles.lastDataDropdown, 'Value', 1);
    
    updateOrderStatus(handles);
    gui_utils('addLog', handles, '数据顺序设置已重置');
end

%% 预览效果
function previewOrder(~, ~, handles)
    handles = get(handles.fig, 'UserData');
    
    % 获取当前设置
    order_mapping = getCurrentOrderMapping(handles);
    
    try
        % 创建预览图
        figure('Name', '数据顺序预览', 'Position', [200, 200, 500, 350]);
        
        % 生成示例数据
        t = 0:0.01:3;
        num_data = 4;  % 示例4个数据
        example_labels = {'数据1', '数据2', '数据3', '数据4'};
        
        % 生成配置
        config = struct();
        config.data_order_mapping = order_mapping;
        config.debug = true;
        config.plot.figure_size = [500, 350];
        
        % 获取样式
        [line_styles, colors, line_widths] = get_simple_data_styles(example_labels, order_mapping, config);
        
        % 绘制示例
        hold on;
        for i = 1:num_data
            y = sin(2*pi*t + (i-1)*pi/4) * exp(-0.1*t);
            plot(t, y, line_styles{i}, 'LineWidth', line_widths(i), ...
                 'Color', colors(i,:), 'DisplayName', example_labels{i});
        end
        
        xlabel('时间 (s)');
        ylabel('示例信号');
        title('数据顺序样式预览');
        legend('Location', 'best');
        grid on;
        
        gui_utils('addLog', handles, '顺序预览已生成');
        
    catch ME
        gui_utils('addLog', handles, sprintf('预览生成失败: %s', ME.message));
    end
end

%% 应用设置
function applyOrder(~, ~, handles)
    handles = get(handles.fig, 'UserData');
    
    % 获取当前设置
    order_mapping = getCurrentOrderMapping(handles);
    
    % 保存到配置中
    if isfield(handles, 'config')
        handles.config.data_order_mapping = order_mapping;
    else
        handles.config = struct();
        handles.config.data_order_mapping = order_mapping;
    end
    
    % 更新句柄
    set(handles.fig, 'UserData', handles);
    
    updateOrderStatus(handles);
    gui_utils('addLog', handles, '数据顺序设置已应用到分析配置');
    
    if ~isempty(fieldnames(order_mapping))
        msgbox('数据顺序设置已应用！运行分析时将使用指定的样式', '应用成功', 'help');
    end
end

%% 获取当前顺序设置
function order_mapping = getCurrentOrderMapping(handles)
    order_mapping = struct();
    
    % 第一个数据
    first_val = get(handles.firstDataDropdown, 'Value');
    if first_val > 1
        order_mapping.first_index = first_val - 1;
    end
    
    % 最后一个数据
    last_val = get(handles.lastDataDropdown, 'Value');
    if last_val > 1
        order_mapping.last_index = last_val - 1;
    end
end

%% 更新状态显示
function updateOrderStatus(handles)
    order_mapping = getCurrentOrderMapping(handles);
    
    status_lines = {};
    
    if isfield(order_mapping, 'first_index')
        status_lines{end+1} = sprintf('📈 第一个: 数据%d (虚线)', order_mapping.first_index);
    else
        status_lines{end+1} = '📈 第一个: 默认第1个 (虚线)';
    end
    
    if isfield(order_mapping, 'last_index')
        status_lines{end+1} = sprintf('🎯 最后一个: 数据%d (黑色)', order_mapping.last_index);
    else
        status_lines{end+1} = '🎯 最后一个: 默认最后1个 (黑色)';
    end
    
    status_lines{end+1} = '🌈 其他: 自动颜色实线';
    
    status_text = strjoin(status_lines, newline);
    set(handles.orderStatusText, 'String', status_text);
end
