function handles = gui_log_viewer(parent, handles)
%% 日志查看器模块
% 负责分析日志的显示和管理
%
% 功能:
% - 实时日志显示
% - 日志滚动
% - 日志长度限制
% - 时间戳显示
%
% 输入:
%   parent - 父容器对象
%   handles - GUI句柄结构体
%
% 输出:  
%   handles - 更新后的句柄结构体

    % 分析执行面板 - 简化，只保留日志
    analysisPanel = uipanel('Parent', parent, ...
                           'Title', '📝 分析日志', ...
                           'Position', [0.02, 0.54, 0.96, 0.44], ...
                           'FontSize', 10, ...
                           'FontWeight', 'bold', ...
                           'ForegroundColor', [0.8, 0.4, 0.1]);
    
    % 日志显示 - 占据整个区域
    uicontrol('Parent', analysisPanel, ...
              'Style', 'text', ...
              'String', '📝 分析日志:', ...
              'Position', [15, 305, 80, 20], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 10, ...
              'FontWeight', 'bold');
    
    handles.logText = uicontrol('Parent', analysisPanel, ...
                               'Style', 'edit', ...
                               'Max', 10, ...
                               'Position', [15, 15, 380, 280], ...
                               'FontSize', 8, ...
                               'HorizontalAlignment', 'left', ...
                               'BackgroundColor', [0.05, 0.05, 0.05], ...
                               'ForegroundColor', [0.2, 0.8, 0.2], ...
                               'FontName', 'Consolas');

end