function handles = gui_log_viewer(parent, handles)
%% 日志查看器模块
% 负责分析日志的显示和管理
%
% 功能:
% - 实时日志显示
% - 日志滚动
% - 日志长度限制
% - 时间戳显示
%
% 输入:
%   parent - 父容器对象
%   handles - GUI句柄结构体
%
% 输出:  
%   handles - 更新后的句柄结构体

    % 分析执行面板 - 简化，只保留日志
    analysisPanel = uipanel('Parent', parent, ...
                           'Title', '📝 分析日志', ...
                           'Units', 'normalized', ...
                           'Position', [0.02, 0.54, 0.96, 0.44], ...
                           'FontSize', 10, ...
                           'FontWeight', 'bold', ...
                           'BackgroundColor', [0.98, 0.99, 0.98], ...
                           'ForegroundColor', [0.80, 0.40, 0.10]);
    
    % 日志显示 - 占据整个区域
    uicontrol('Parent', analysisPanel, ...
              'Style', 'text', ...
              'Units', 'normalized', ...
              'String', '📝 分析日志:', ...
              'Position', [0.03, 0.88, 0.40, 0.10], ...
              'HorizontalAlignment', 'left', ...
              'FontSize', 10, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.98, 0.99, 0.98]);
    
    handles.logText = uicontrol('Parent', analysisPanel, ...
                               'Style', 'edit', ...
                               'Tag', 'ConsoleLog', ...
                               'Max', 10, ...
                               'Units', 'normalized', ...
                               'Position', [0.03, 0.05, 0.94, 0.80], ...
                               'FontSize', 8, ...
                               'HorizontalAlignment', 'left', ...
                               'BackgroundColor', [0.05, 0.05, 0.05], ...
                               'ForegroundColor', [0.20, 0.80, 0.20], ...
                               'FontName', 'Consolas');

end
