function handles = gui_fdei_analysis(parent, handles)
%GUI_FDEI_ANALYSIS Build the FDEI analysis page.
%   The page separates batch simulation controls from the result-analysis
%   and drawing controls. Core calculations remain in src/analysis/fdei.

if nargin < 2 || ~isstruct(handles) || ~isfield(handles, 'fig')
    error('gui_fdei_analysis:InvalidHandles', '需要有效的 GUI handles。');
end
fig = handles.fig;
theme = handles.theme;
cfg = fdei_default_config();

header = uipanel('Parent', parent, 'BorderType', 'none', ...
    'Position', [0.015, 0.905, 0.97, 0.075], ...
    'BackgroundColor', theme.primary);
uicontrol('Parent', header, 'Style', 'text', ...
    'String', 'FDEI 频域等效阻抗分析', 'Units', 'normalized', ...
    'Position', [0.025, 0.34, 0.55, 0.46], 'HorizontalAlignment', 'left', ...
    'FontSize', 15, 'FontWeight', 'bold', ...
    'ForegroundColor', theme.onPrimary, 'BackgroundColor', theme.primary);
uicontrol('Parent', header, 'Style', 'text', ...
    'String', '批量仿真 · 稳态辨识 · 减振器端口/总悬架 FDEI 图1/图2', ...
    'Units', 'normalized', 'Position', [0.025, 0.08, 0.75, 0.27], ...
    'HorizontalAlignment', 'left', 'FontSize', 9, ...
    'ForegroundColor', theme.primarySoftText, 'BackgroundColor', theme.primary);

subTabs = uitabgroup('Parent', parent, 'Position', [0.008, 0.015, 0.984, 0.875]);
batchTab = uitab(subTabs, 'Title', '① 批量仿真', 'BackgroundColor', theme.canvas);
plotTab = uitab(subTabs, 'Title', '② 分析绘图', 'BackgroundColor', theme.canvas);

batchUi = createBatchPage(batchTab, cfg, theme, fig);
plotUi = createPlotPage(plotTab, cfg, theme, fig);
fdei = struct('schema_version', 1, 'config', cfg, 'isRunning', false, ...
    'stopRequested', false, 'lastResults', table(), 'lastSummary', table(), ...
    'lastFigures', {{}}, 'subTabGroup', subTabs, 'batchTab', batchTab, ...
    'plotTab', plotTab, 'batchUi', batchUi, 'plotUi', plotUi, ...
    'ui', struct('subTabGroup', subTabs, 'batchTab', batchTab, ...
    'plotTab', plotTab));
handles.fdei = fdei;
set(fig, 'UserData', handles);
end

function ui = createBatchPage(parent, cfg, theme, fig)
modelPanel = uipanel('Parent', parent, 'Title', '模型与 Variant 设置', ...
    'Position', [0.015, 0.805, 0.97, 0.175], 'FontSize', 11, ...
    'FontWeight', 'bold', 'BackgroundColor', theme.surface);
modelEdit = addEdit(modelPanel, '模型文件', cfg.model, [0.02 0.56 0.65 0.22]);
browseModelButton = uicontrol('Parent', modelPanel, 'Style', 'pushbutton', ...
    'String', '浏览...', 'Units', 'normalized', ...
    'Position', [0.68 0.56 0.10 0.22], 'Callback', @onBrowseModel);
signalMappingButton = uicontrol('Parent', modelPanel, 'Style', 'pushbutton', ...
    'String', '信号映射 / 手工工况', 'Units', 'normalized', ...
    'Position', [0.80 0.56 0.17 0.22], 'Callback', @onEditSignalMapping);
variantPathEdit = addEdit(modelPanel, 'Variant 子系统', cfg.variantSubsystemPath, ...
    [0.02 0.18 0.36 0.22]);
roadPathEdit = addEdit(modelPanel, '道路选择块', cfg.roadSelectPath, ...
    [0.42 0.18 0.36 0.22]);
roadValueEdit = addEdit(modelPanel, '道路值', cfg.roadSelectValue, ...
    [0.82 0.18 0.15 0.22]);

runPanel = uipanel('Parent', parent, 'Title', '扫频与保存设置', ...
    'Position', [0.015, 0.625, 0.97, 0.16], 'FontSize', 11, ...
    'FontWeight', 'bold', 'BackgroundColor', theme.surface);
frequencyEdit = addStackedEdit(runPanel, '频率 Hz', joinNumbers(cfg.frequencyHz), ...
    [0.02 0.54 0.44 0.18]);
uicontrol('Parent', runPanel, 'Style', 'text', 'String', '幅值模式', ...
    'Units', 'normalized', 'Position', [0.48 0.73 0.18 0.09], ...
    'HorizontalAlignment', 'left');
amplitudeModePopup = uicontrol('Parent', runPanel, 'Style', 'popupmenu', ...
    'String', {'legacy_A_over_f','constant_velocity','constant_displacement','manual'}, ...
    'Value', 1, 'Units', 'normalized', 'Position', [0.48 0.54 0.18 0.18]);
amplitudeScaleEdit = addStackedEdit(runPanel, 'A/f', ...
    num2str(cfg.legacyAmplitudeScale), [0.70 0.54 0.12 0.18]);
settlingTimeEdit = addStackedEdit(runPanel, '稳态时间 s', ...
    num2str(cfg.minimumSettlingTime_s), [0.02 0.08 0.15 0.17]);
savedCyclesEdit = addStackedEdit(runPanel, '保留周期', ...
    num2str(cfg.savedCycles), [0.20 0.08 0.15 0.17]);
samplesPerCycleEdit = addStackedEdit(runPanel, '采样点/周期', ...
    num2str(cfg.samplesPerCycle), [0.38 0.08 0.15 0.17]);
velocityAmplitudeEdit = addStackedEdit(runPanel, '速度幅值 m/s', ...
    num2str(cfg.constantRoadVelocityPeak_mps), [0.56 0.08 0.18 0.17]);
displacementAmplitudeEdit = addStackedEdit(runPanel, '位移幅值 m', ...
    num2str(cfg.constantRoadDisplacement_m), [0.77 0.08 0.20 0.17]);

algorithmPanel = uipanel('Parent', parent, ...
    'Title', '参与算法（CRFRS 项按通用辨识处理）', ...
    'Position', [0.015, 0.17, 0.505, 0.435], 'FontSize', 11, ...
    'FontWeight', 'bold', 'BackgroundColor', theme.surface);
registry = fdei_algorithm_registry();
defaultRows = min(4, numel(registry));
tableData = cell(defaultRows, 3);
for registryIndex = 1:defaultRows
    tableData(registryIndex,:) = {true, registry(registryIndex).Name, ...
        registry(registryIndex).Variant};
end
algorithmTable = uitable('Parent', algorithmPanel, 'Units', 'normalized', ...
    'Position', [0.02 0.08 0.96 0.86], 'Data', tableData, ...
    'ColumnName', {'参与','算法名称','Variant 标签'}, ...
    'ColumnFormat', {'logical','char','char'}, ...
    'ColumnEditable', [true true true], 'RowName', []);

logPanel = uipanel('Parent', parent, 'Title', '执行日志与进度', ...
    'Position', [0.535, 0.17, 0.45, 0.435], 'FontSize', 11, ...
    'FontWeight', 'bold', 'BackgroundColor', theme.surface);
executionLogText = uicontrol('Parent', logPanel, 'Style', 'edit', ...
    'Tag', 'ConsoleLog', 'Max', 10, 'Units', 'normalized', ...
    'Position', [0.03 0.23 0.94 0.68], 'HorizontalAlignment', 'left', ...
    'BackgroundColor', theme.console, 'ForegroundColor', theme.consoleText, ...
    'FontName', theme.monoFont);
progressText = uicontrol('Parent', logPanel, 'Style', 'text', 'String', '未开始', ...
    'Units', 'normalized', 'Position', [0.03 0.135 0.24 0.065], ...
    'HorizontalAlignment', 'left');
progressBackground = uipanel('Parent', logPanel, 'BorderType', 'line', ...
    'Units', 'normalized', 'Position', [0.28 0.145 0.69 0.045], ...
    'BackgroundColor', theme.surfaceAlt, 'ForegroundColor', theme.border);
progressFill = uipanel('Parent', progressBackground, 'BorderType', 'none', ...
    'Units', 'normalized', 'Position', [0 0 0 1], ...
    'BackgroundColor', theme.accent);
statusText = uicontrol('Parent', logPanel, 'Style', 'text', 'String', ...
    '请先填写模型、Variant 和信号映射。', 'Units', 'normalized', ...
    'Position', [0.03 0.02 0.94 0.08], 'HorizontalAlignment', 'left');

actionPanel = uipanel('Parent', parent, 'Title', '输出与执行', ...
    'Position', [0.015, 0.015, 0.97, 0.135], 'FontSize', 11, ...
    'FontWeight', 'bold', 'BackgroundColor', theme.surface);
outputDirLabel = uicontrol('Parent', actionPanel, 'Style', 'text', ...
    'String', '输出目录', 'Units', 'normalized', ...
    'Position', [0.02 0.505 0.07 0.27], 'HorizontalAlignment', 'left');
outputDirEdit = uicontrol('Parent', actionPanel, 'Style', 'edit', ...
    'String', cfg.outputDir, 'Units', 'normalized', ...
    'BackgroundColor', 'white', 'Position', [0.09 0.48 0.36 0.32]);
browseOutputDirButton = uicontrol('Parent', actionPanel, 'Style', 'pushbutton', ...
    'String', '浏览...', 'Units', 'normalized', ...
    'Position', [0.46 0.48 0.07 0.32], 'Callback', @onBrowseOutputDir);
checkpointCheck = uicontrol('Parent', actionPanel, 'Style', 'checkbox', ...
    'String', '保留 checkpoint', 'Value', 1, 'Units', 'normalized', ...
    'Position', [0.56 0.50 0.12 0.28]);
stopOnErrorCheck = uicontrol('Parent', actionPanel, 'Style', 'checkbox', ...
    'String', '失败即停', 'Value', 1, 'Units', 'normalized', ...
    'Position', [0.69 0.50 0.09 0.28]);
validateButton = uicontrol('Parent', actionPanel, 'Style', 'pushbutton', ...
    'String', '检查配置', 'Units', 'normalized', 'Position', [0.80 0.48 0.08 0.32], ...
    'Callback', @onValidateBatch);
runButton = uicontrol('Parent', actionPanel, 'Style', 'pushbutton', ...
    'String', '开始批量仿真', 'FontWeight', 'bold', 'Units', 'normalized', ...
    'Position', [0.89 0.48 0.09 0.32], 'Callback', @onRunBatch);
stopButton = uicontrol('Parent', actionPanel, 'Style', 'pushbutton', ...
    'String', '请求停止', 'Units', 'normalized', ...
    'Position', [0.82 0.08 0.16 0.30], 'Enable', 'off', ...
    'Callback', @onStopBatch);
exportConfigButton = uicontrol('Parent', actionPanel, 'Style', 'pushbutton', ...
    'String', '导出配置', 'Units', 'normalized', ...
    'Position', [0.56 0.08 0.11 0.30], 'Callback', @onExportConfig);
importConfigButton = uicontrol('Parent', actionPanel, 'Style', 'pushbutton', ...
    'String', '导入配置', 'Units', 'normalized', ...
    'Position', [0.69 0.08 0.11 0.30], 'Callback', @onImportConfig);

ui = struct('modelPanel', modelPanel, 'runPanel', runPanel, ...
    'algorithmPanel', algorithmPanel, 'logPanel', logPanel, ...
    'actionPanel', actionPanel, 'modelEdit', modelEdit, ...
    'variantPathEdit', variantPathEdit, ...
    'roadPathEdit', roadPathEdit, 'roadValueEdit', roadValueEdit, ...
    'browseModelButton', browseModelButton, ...
    'signalMappingButton', signalMappingButton, ...
    'frequencyEdit', frequencyEdit, 'amplitudeModePopup', amplitudeModePopup, ...
    'amplitudeScaleEdit', amplitudeScaleEdit, ...
    'velocityAmplitudeEdit', velocityAmplitudeEdit, ...
    'displacementAmplitudeEdit', displacementAmplitudeEdit, ...
    'settlingTimeEdit', settlingTimeEdit, 'savedCyclesEdit', savedCyclesEdit, ...
    'samplesPerCycleEdit', samplesPerCycleEdit, 'algorithmTable', algorithmTable, ...
    'outputDirLabel', outputDirLabel, 'outputDirEdit', outputDirEdit, ...
    'browseOutputDirButton', browseOutputDirButton, ...
    'checkpointCheck', checkpointCheck, ...
    'stopOnErrorCheck', stopOnErrorCheck, 'validateButton', validateButton, ...
    'runButton', runButton, 'stopButton', stopButton, ...
    'exportConfigButton', exportConfigButton, ...
    'importConfigButton', importConfigButton, ...
    'executionLogText', executionLogText, ...
    'progressBackground', progressBackground, 'progressFill', progressFill, ...
    'progressText', progressText, ...
    'statusText', statusText);

function onBrowseModel(src, ~)
figHandle = ancestor(src, 'figure');
handles = latestHandles(figHandle);
modelValue = char(string(get(handles.fdei.batchUi.modelEdit, 'String')));
startLocation = pwd;
if ismember(exist(modelValue, 'file'), [2 4])
    startLocation = modelValue;
elseif exist(fileparts(modelValue), 'dir') == 7
    startLocation = fileparts(modelValue);
end
[fileName, folder] = uigetfile( ...
    {'*.slx;*.mdl', 'Simulink 模型 (*.slx, *.mdl)'; '*.*', '所有文件'}, ...
    '选择 FDEI Simulink 模型', startLocation);
if isequal(fileName, 0)
    return;
end
modelFile = fullfile(folder, fileName);
set(handles.fdei.batchUi.modelEdit, 'String', modelFile);
handles.fdei.config.model = modelFile;
set(handles.fdei.batchUi.statusText, 'String', ['已选择模型：' modelFile]);
set(figHandle, 'UserData', handles);
end

function onBrowseOutputDir(src, ~)
figHandle = ancestor(src, 'figure');
handles = latestHandles(figHandle);
currentDir = char(string(get(handles.fdei.batchUi.outputDirEdit, 'String')));
if exist(currentDir, 'dir') ~= 7
    currentDir = pwd;
end
selectedDir = uigetdir(currentDir, '选择 FDEI 输出目录');
if isequal(selectedDir, 0)
    return;
end
set(handles.fdei.batchUi.outputDirEdit, 'String', selectedDir);
handles.fdei.config.outputDir = selectedDir;
handles.fdei.config.batchOutputDir = selectedDir;
set(handles.fdei.batchUi.statusText, 'String', ...
    ['已选择输出目录：' selectedDir]);
set(figHandle, 'UserData', handles);
end

function onExportConfig(src, ~)
figHandle = ancestor(src, 'figure');
handles = latestHandles(figHandle);
try
    exportCfg = fdei_config_utils('readbatchdraft', ...
        handles.fdei.batchUi, handles.fdei.config);
    exportCfg = fdei_config_utils('readanalysis', ...
        handles.fdei.plotUi, exportCfg);
catch exception
    set(handles.fdei.batchUi.statusText, 'String', ...
        ['无法导出配置：' exception.message]);
    return;
end
[fileName, folder] = uiputfile('*.mat', '导出 FDEI 配置', ...
    fullfile(pwd, 'FDEI_config.mat'));
if isequal(fileName, 0)
    return;
end
try
    savedFile = fdei_save_config(fullfile(folder, fileName), exportCfg);
    handles.fdei.config = exportCfg;
    set(handles.fdei.batchUi.statusText, 'String', ['配置已导出：' savedFile]);
    appendLog(figHandle, ['FDEI 配置已导出：' savedFile]);
    set(figHandle, 'UserData', handles);
catch exception
    set(handles.fdei.batchUi.statusText, 'String', ...
        ['配置导出失败：' exception.message]);
end
end

function onImportConfig(src, ~)
figHandle = ancestor(src, 'figure');
handles = latestHandles(figHandle);
[fileName, folder] = uigetfile('*.mat', '导入 FDEI 配置');
if isequal(fileName, 0)
    return;
end
oldCfg = handles.fdei.config;
try
    importedCfg = fdei_load_config(fullfile(folder, fileName), oldCfg);
    fdei_config_utils('applybatch', handles.fdei.batchUi, importedCfg);
    fdei_config_utils('applyanalysis', handles.fdei.plotUi, importedCfg);
catch exception
    fdei_config_utils('applybatch', handles.fdei.batchUi, oldCfg);
    fdei_config_utils('applyanalysis', handles.fdei.plotUi, oldCfg);
    set(handles.fdei.batchUi.statusText, 'String', ...
        ['配置导入失败：' exception.message]);
    return;
end
handles.fdei.config = importedCfg;
configFile = fullfile(folder, fileName);
set(handles.fdei.batchUi.statusText, 'String', ['配置已导入：' configFile]);
set(handles.fdei.plotUi.statusText, 'String', '分析参数已从配置文件更新。');
appendLog(figHandle, ['FDEI 配置已导入：' configFile]);
set(figHandle, 'UserData', handles);
end

function onEditSignalMapping(src, ~)
figHandle = ancestor(src, 'figure');
handles = latestHandles(figHandle);
currentCfg = handles.fdei.config;
prompts = { ...
    '参数工作区（model/base）'; ...
    '信号来源（logsout/simulationoutput）'; ...
    'logsout 变量'; ...
    '时间变量'; ...
    'vs（簧载速度）'; ...
    'as（簧载加速度）'; ...
    'vd（相对速度，可与 vu 二选一）'; ...
    'vu（非簧载速度，可与 vd 二选一）'; ...
    'Fd（总阻尼力，可与 cCmd 二选一）'; ...
    'cCmd（控制阻尼，可与 Fd 二选一）'; ...
    'xr（路面位移，可选）'; ...
    'xu（非簧载位移，可选）'; ...
    'tireDef（轮胎挠度，可选）'; ...
    'suspDef（悬架挠度，可选）'; ...
    '手工工况：频率,幅值；频率,幅值'};
defaults = {currentCfg.parameterWorkspace; currentCfg.signalSource; ...
    currentCfg.logsoutVariable; currentCfg.timeVariable; ...
    currentCfg.signal.vs; currentCfg.signal.as; currentCfg.signal.vd; ...
    currentCfg.signal.vu; currentCfg.signal.Fd; currentCfg.signal.cCmd; ...
    currentCfg.signal.xr; currentCfg.signal.xu; currentCfg.signal.tireDef; ...
    currentCfg.signal.suspDef; formatManualCases(currentCfg.manualSineCases)};
answers = inputdlg(prompts, 'FDEI 信号映射与手工扫频工况', ...
    repmat([1 72], numel(prompts), 1), defaults);
if isempty(answers)
    return;
end
try
    currentCfg.parameterWorkspace = strtrim(answers{1});
    currentCfg.signalSource = strtrim(answers{2});
    currentCfg.logsoutVariable = strtrim(answers{3});
    currentCfg.timeVariable = strtrim(answers{4});
    signalNames = {'vs','as','vd','vu','Fd','cCmd','xr','xu','tireDef','suspDef'};
    for signalIndex = 1:numel(signalNames)
        currentCfg.signal.(signalNames{signalIndex}) = ...
            strtrim(answers{signalIndex+4});
    end
    currentCfg.manualSineCases = fdei_config_utils( ...
        'parsemanualcases', answers{15});
catch exception
    set(handles.fdei.batchUi.statusText, 'String', ...
        ['信号映射未保存：' exception.message]);
    return;
end
handles.fdei.config = currentCfg;
set(handles.fdei.batchUi.statusText, 'String', ...
    '信号映射已保存；运行前请执行“检查配置”。');
set(figHandle, 'UserData', handles);
end

function onValidateBatch(src, ~)
figHandle = ancestor(src, 'figure');
handles = latestHandles(figHandle);
try
    batchCfg = fdei_config_utils('readbatch', handles.fdei.batchUi, handles.fdei.config);
    handles.fdei.config = batchCfg;
    set(handles.fdei.batchUi.statusText, 'String', '配置检查通过。');
    appendLog(figHandle, 'FDEI 批量配置检查通过。');
catch exception
    set(handles.fdei.batchUi.statusText, 'String', ['配置错误：' exception.message]);
    appendLog(figHandle, ['配置错误：' exception.message]);
end
set(figHandle, 'UserData', handles);
end

function onRunBatch(src, ~)
figHandle = ancestor(src, 'figure');
handles = latestHandles(figHandle);
if handles.fdei.isRunning
    return;
end
try
    batchCfg = fdei_config_utils('readbatch', handles.fdei.batchUi, handles.fdei.config);
catch exception
    appendLog(figHandle, ['无法开始：' exception.message]);
    return;
end
handles.fdei.config = batchCfg;
handles.fdei.isRunning = true;
handles.fdei.stopRequested = false;
fdei_config_utils('updateprogress', handles.fdei.batchUi, 0, 0, '正在准备...');
set(handles.fdei.batchUi.runButton, 'Enable', 'off');
set(handles.fdei.batchUi.stopButton, 'Enable', 'on');
set(figHandle, 'UserData', handles);
try
    [~, ~, files] = fdei_run_batch(batchCfg, ...
        'ProgressFcn', @(done,total,row) batchProgress(figHandle,done,total,row), ...
        'LogFcn', @(message) appendLog(figHandle,message), ...
        'StopFcn', @(done,total) batchStopRequested(figHandle,done,total));
    appendLog(figHandle, ['批量结果已保存：' files.mat]);
catch exception
    appendLog(figHandle, ['批量仿真结束：' exception.message]);
end
handles = latestHandles(figHandle);
handles.fdei.isRunning = false;
set(handles.fdei.batchUi.runButton, 'Enable', 'on');
set(handles.fdei.batchUi.stopButton, 'Enable', 'off');
set(figHandle, 'UserData', handles);
end

function onStopBatch(src, ~)
figHandle = ancestor(src, 'figure');
handles = latestHandles(figHandle);
handles.fdei.stopRequested = true;
set(figHandle, 'UserData', handles);
appendLog(figHandle, '已请求在下一个工况边界停止。');
end

function batchProgress(figHandle, done, total, row)
handles = latestHandles(figHandle);
fdei_config_utils('updateprogress', handles.fdei.batchUi, ...
    done, total, row.Status);
drawnow;
end

function value = batchStopRequested(figHandle, ~, ~)
handles = latestHandles(figHandle);
value = handles.fdei.stopRequested;
drawnow;
end
end

function ui = createPlotPage(parent, cfg, theme, fig)
sourcePanel = uipanel('Parent', parent, 'Title', '结果文件与筛选', ...
    'Position', [0.015, 0.59, 0.30, 0.39], 'FontSize', 11, ...
    'FontWeight', 'bold', 'BackgroundColor', theme.surface);
uicontrol('Parent', sourcePanel, 'Style', 'text', ...
    'String', '已选择的 MAT 文件', 'Units', 'normalized', ...
    'Position', [0.04 0.88 0.92 0.06], 'HorizontalAlignment', 'left', ...
    'ForegroundColor', theme.mutedText);
sourceFileList = uicontrol('Parent', sourcePanel, 'Style', 'listbox', ...
    'Max', 2, 'Min', 0, 'String', {}, 'Units', 'normalized', ...
    'Position', [0.04 0.55 0.92 0.32]);
uicontrol('Parent', sourcePanel, 'Style', 'text', 'String', '频率筛选 Hz', ...
    'Units', 'normalized', 'Position', [0.04 0.44 0.26 0.07], ...
    'HorizontalAlignment', 'left');
frequencyFilterEdit = uicontrol('Parent', sourcePanel, 'Style', 'edit', ...
    'String', '', 'Units', 'normalized', 'BackgroundColor', 'white', ...
    'Position', [0.31 0.43 0.65 0.09]);
uicontrol('Parent', sourcePanel, 'Style', 'text', 'String', '算法筛选', ...
    'Units', 'normalized', 'Position', [0.04 0.29 0.26 0.07], ...
    'HorizontalAlignment', 'left');
strategyList = uicontrol('Parent', sourcePanel, 'Style', 'listbox', ...
    'String', {'all','Passive','Skyhook','ADD','SHADD','FRS_c','CRFRSas_c','CRFRSvs_c'}, ...
    'Value', 1, 'Max', 8, 'Min', 1, 'Units', 'normalized', ...
    'Position', [0.31 0.22 0.65 0.18]);
browseButton = uicontrol('Parent', sourcePanel, 'Style', 'pushbutton', ...
    'String', '选择 MAT', 'Units', 'normalized', 'Position', [0.04 0.06 0.28 0.11], ...
    'Callback', @onBrowseResults);
discoverButton = uicontrol('Parent', sourcePanel, 'Style', 'pushbutton', ...
    'String', '自动发现', 'Units', 'normalized', 'Position', [0.36 0.06 0.28 0.11], ...
    'Callback', @onDiscoverResults);
runAnalysisButton = uicontrol('Parent', sourcePanel, 'Style', 'pushbutton', ...
    'String', '运行分析', 'FontWeight', 'bold', 'Units', 'normalized', ...
    'Position', [0.68 0.06 0.28 0.11], 'Callback', @onRunAnalysis);

parameterPanel = uipanel('Parent', parent, 'Title', '辨识参数与符号约定', ...
    'Position', [0.33, 0.59, 0.655, 0.39], 'FontSize', 11, ...
    'FontWeight', 'bold', 'BackgroundColor', theme.surface);
uicontrol('Parent', parameterPanel, 'Style', 'text', 'String', '物理参数', ...
    'Units', 'normalized', 'Position', [0.03 0.91 0.30 0.06], ...
    'HorizontalAlignment', 'left', 'FontWeight', 'bold', ...
    'ForegroundColor', theme.primary);
cMinEdit = addStackedEdit(parameterPanel, '最小阻尼 cMin', ...
    num2str(cfg.cMin), [0.03 0.69 0.20 0.12]);
cMaxEdit = addStackedEdit(parameterPanel, '最大阻尼 cMax', ...
    num2str(cfg.cMax), [0.275 0.69 0.20 0.12]);
ksEdit = addStackedEdit(parameterPanel, '悬架刚度 ks', ...
    num2str(cfg.ks), [0.52 0.69 0.20 0.12]);
alphaEdit = addStackedEdit(parameterPanel, '滤波参数 alpha (rad/s)', ...
    num2str(cfg.alpha), [0.765 0.69 0.20 0.12]);
uicontrol('Parent', parameterPanel, 'Style', 'text', 'String', '符号约定', ...
    'Units', 'normalized', 'Position', [0.03 0.59 0.30 0.06], ...
    'HorizontalAlignment', 'left', 'FontWeight', 'bold', ...
    'ForegroundColor', theme.primary);
vdSignPopup = makeSignPopup(parameterPanel, {'vd sign +1','vd sign -1'}, ...
    cfg.vdToCanonicalSign, [0.03 0.45 0.20 0.12]);
forceSignPopup = makeSignPopup(parameterPanel, ...
    {'force sign +1','force sign -1'}, cfg.forceToCanonicalSign, ...
    [0.275 0.45 0.20 0.12]);
switchSignPopup = makeSignPopup(parameterPanel, ...
    {'switch sign +1','switch sign -1'}, cfg.switchPolarity, ...
    [0.52 0.45 0.20 0.12]);
zeroStatePopup = makeSignPopup(parameterPanel, ...
    {'zero state +1','zero state -1'}, cfg.zeroSwitchState, ...
    [0.765 0.45 0.20 0.12]);
uicontrol('Parent', parameterPanel, 'Style', 'text', 'String', '分析设置', ...
    'Units', 'normalized', 'Position', [0.03 0.34 0.30 0.06], ...
    'HorizontalAlignment', 'left', 'FontWeight', 'bold', ...
    'ForegroundColor', theme.primary);
lastNCyclesEdit = addStackedEdit(parameterPanel, '分析周期', ...
    num2str(cfg.lastNCycles), [0.03 0.12 0.20 0.12]);
harmonicOrderEdit = addStackedEdit(parameterPanel, '谐波阶数', ...
    num2str(cfg.harmonicOrder), [0.275 0.12 0.20 0.12]);
forceBaselineDampingEdit = addStackedEdit(parameterPanel, '基准阻尼', ...
    num2str(cfg.forceBaselineDamping), [0.52 0.12 0.20 0.12]);
uicontrol('Parent', parameterPanel, 'Style', 'text', 'String', '力输入', ...
    'Units', 'normalized', 'Position', [0.765 0.25 0.20 0.09], ...
    'HorizontalAlignment', 'left');
forceModePopup = uicontrol('Parent', parameterPanel, 'Style', 'popupmenu', ...
    'String', {'total','control_increment'}, 'Value', 2, ...
    'Units', 'normalized', 'Position', [0.765 0.12 0.20 0.12]);

resultPanel = uipanel('Parent', parent, 'Title', '分析结果', ...
    'Position', [0.015, 0.19, 0.97, 0.38], 'FontSize', 11, ...
    'FontWeight', 'bold', 'BackgroundColor', theme.surface);
uicontrol('Parent', resultPanel, 'Style', 'text', 'String', '逐工况明细', ...
    'Units', 'normalized', 'Position', [0.02 0.88 0.64 0.06], ...
    'HorizontalAlignment', 'left', 'FontWeight', 'bold', ...
    'ForegroundColor', theme.mutedText);
uicontrol('Parent', resultPanel, 'Style', 'text', 'String', '算法汇总', ...
    'Units', 'normalized', 'Position', [0.68 0.88 0.30 0.06], ...
    'HorizontalAlignment', 'left', 'FontWeight', 'bold', ...
    'ForegroundColor', theme.mutedText);
resultTable = uitable('Parent', resultPanel, 'Units', 'normalized', ...
    'Position', [0.02 0.13 0.64 0.74], 'Data', {}, 'RowName', []);
summaryTable = uitable('Parent', resultPanel, 'Units', 'normalized', ...
    'Position', [0.68 0.13 0.30 0.74], 'Data', {}, 'RowName', []);
statusText = uicontrol('Parent', resultPanel, 'Style', 'text', ...
    'String', '未加载分析结果。', 'Units', 'normalized', ...
    'Position', [0.02 0.025 0.96 0.065], 'HorizontalAlignment', 'left');

buttonPanel = uipanel('Parent', parent, 'Title', '图形与导出', ...
    'Position', [0.015, 0.025, 0.97, 0.14], 'FontSize', 11, ...
    'FontWeight', 'bold', 'BackgroundColor', theme.surface);
figure1Button = uicontrol('Parent', buttonPanel, 'Style', 'pushbutton', ...
    'String', '预览图1：减振器端口', 'Units', 'normalized', ...
    'Position', [0.02 0.28 0.18 0.42], 'Callback', @onFigure1);
figure2Button = uicontrol('Parent', buttonPanel, 'Style', 'pushbutton', ...
    'String', '预览图2：总悬架', 'Units', 'normalized', ...
    'Position', [0.215 0.28 0.18 0.42], 'Callback', @onFigure2);
exportButton = uicontrol('Parent', buttonPanel, 'Style', 'pushbutton', ...
    'String', '导出结果 MAT/CSV', 'Units', 'normalized', ...
    'Position', [0.41 0.28 0.18 0.42], 'Callback', @onExportResults);
uicontrol('Parent', buttonPanel, 'Style', 'text', ...
    'String', '图1/图2均为 FDEI 等效 c、b、k；图3-7暂未纳入首版。', ...
    'Units', 'normalized', 'Position', [0.62 0.22 0.36 0.48], ...
    'HorizontalAlignment', 'left');

ui = struct('sourcePanel', sourcePanel, 'parameterPanel', parameterPanel, ...
    'resultPanel', resultPanel, 'buttonPanel', buttonPanel, ...
    'sourceFileList', sourceFileList, 'browseButton', browseButton, ...
    'discoverButton', discoverButton, 'runAnalysisButton', runAnalysisButton, ...
    'cMinEdit', cMinEdit, 'cMaxEdit', cMaxEdit, 'ksEdit', ksEdit, ...
    'alphaEdit', alphaEdit, 'lastNCyclesEdit', lastNCyclesEdit, ...
    'harmonicOrderEdit', harmonicOrderEdit, ...
    'forceBaselineDampingEdit', forceBaselineDampingEdit, ...
    'forceModePopup', forceModePopup, 'frequencyFilterEdit', frequencyFilterEdit, ...
    'vdSignPopup', vdSignPopup, 'forceSignPopup', forceSignPopup, ...
    'switchSignPopup', switchSignPopup, 'zeroStatePopup', zeroStatePopup, ...
    'strategyList', strategyList, 'resultTable', resultTable, ...
    'summaryTable', summaryTable, 'statusText', statusText, ...
    'figure1Button', figure1Button, 'figure2Button', figure2Button, ...
    'exportButton', exportButton);

function onBrowseResults(src, ~)
figHandle = ancestor(src, 'figure');
[fileName, filePath] = uigetfile('*.mat', '选择 FDEI 批量结果', 'MultiSelect', 'on');
if isequal(fileName, 0)
    return;
end
if ischar(fileName)
    fileName = {fileName};
end
handles = latestHandles(figHandle);
files = cellfun(@(name) fullfile(filePath, name), fileName, 'UniformOutput', false);
set(handles.fdei.plotUi.sourceFileList, 'String', files, 'Value', 1:numel(files));
set(handles.fdei.plotUi.statusText, 'String', sprintf('已选择 %d 个 MAT 文件。', numel(files)));
set(figHandle, 'UserData', handles);
end

function onDiscoverResults(src, ~)
figHandle = ancestor(src, 'figure');
handles = latestHandles(figHandle);
outputDir = handles.fdei.config.outputDir;
files = dir(fullfile(outputDir, 'FDEI_batch_runs*.mat'));
fileNames = arrayfun(@(item) fullfile(item.folder, item.name), files, ...
    'UniformOutput', false);
if isempty(fileNames)
    set(handles.fdei.plotUi.sourceFileList, 'String', fileNames, 'Value', []);
else
    set(handles.fdei.plotUi.sourceFileList, 'String', fileNames, ...
        'Value', 1:numel(fileNames));
end
set(handles.fdei.plotUi.statusText, 'String', sprintf('自动发现 %d 个文件。', numel(fileNames)));
set(figHandle, 'UserData', handles);
end

function onRunAnalysis(src, ~)
figHandle = ancestor(src, 'figure');
handles = latestHandles(figHandle);
files = get(handles.fdei.plotUi.sourceFileList, 'String');
if ischar(files)
    files = {files};
end
if isempty(files)
    set(handles.fdei.plotUi.statusText, 'String', '请先选择 MAT 文件。');
    return;
end
try
    analysisCfg = fdei_config_utils('readanalysis', handles.fdei.plotUi, ...
        handles.fdei.config);
    [runs, ~, ~, ~] = fdei_load_batch_results(files, analysisCfg);
    [results, summary, context] = fdei_analyze_runs(runs, analysisCfg);
    handles.fdei.config = context.cfg;
    handles.fdei.lastResults = results;
    handles.fdei.lastSummary = summary;
    setTableFromTable(handles.fdei.plotUi.resultTable, results);
    setTableFromTable(handles.fdei.plotUi.summaryTable, summary);
    set(handles.fdei.plotUi.statusText, 'String', ...
        sprintf('分析完成：%d 条 runs。', height(results)));
catch exception
    set(handles.fdei.plotUi.statusText, 'String', ['分析错误：' exception.message]);
end
set(figHandle, 'UserData', handles);
end

function onFigure1(src, ~)
showFigure(src, 1);
end

function onFigure2(src, ~)
showFigure(src, 2);
end

function showFigure(src, figureIndex)
figHandle = ancestor(src, 'figure');
handles = latestHandles(figHandle);
if isempty(handles.fdei.lastResults)
    set(handles.fdei.plotUi.statusText, 'String', '请先运行分析。');
    return;
end
plotCfg = handles.fdei.config;
plotCfg.saveFigures = false;
allFigures = fdei_plot_figures12(handles.fdei.lastResults, plotCfg, ...
    'Visible', 'off');
keepFigure = allFigures{figureIndex};
set(keepFigure, 'Visible', 'on');
otherFigure = allFigures{3-figureIndex};
if isgraphics(otherFigure)
    delete(otherFigure);
end
handles.fdei.lastFigures = {keepFigure};
set(figHandle, 'UserData', handles);
set(handles.fdei.plotUi.statusText, 'String', sprintf('图%d 已打开。', figureIndex));
end

function onExportResults(src, ~)
figHandle = ancestor(src, 'figure');
handles = latestHandles(figHandle);
if isempty(handles.fdei.lastResults)
    set(handles.fdei.plotUi.statusText, 'String', '请先运行分析。');
    return;
end
[fileName, filePath] = uiputfile('FDEI_analysis_results.mat', '保存分析结果');
if isequal(fileName, 0)
    return;
end
results = handles.fdei.lastResults; %#ok<NASGU>
summary = handles.fdei.lastSummary; %#ok<NASGU>
save(fullfile(filePath, fileName), 'results', 'summary', '-v7.3');
[folder, base] = fileparts(fullfile(filePath, fileName));
writetable(results, fullfile(folder, [base '_per_run.csv']));
writetable(summary, fullfile(folder, [base '_summary.csv']));
set(handles.fdei.plotUi.statusText, 'String', ['已导出：' fullfile(filePath, fileName)]);
end
end

function control = addEdit(parent, label, value, position)
uicontrol('Parent', parent, 'Style', 'text', 'String', label, ...
    'Units', 'normalized', 'Position', [position(1), position(2)+0.02, ...
    0.12, 0.15], 'HorizontalAlignment', 'left');
control = uicontrol('Parent', parent, 'Style', 'edit', ...
    'String', value, 'Units', 'normalized', 'BackgroundColor', 'white', ...
    'Position', [position(1)+0.12, position(2), position(3)-0.12, position(4)]);
end

function control = addStackedEdit(parent, label, value, position)
uicontrol('Parent', parent, 'Style', 'text', 'String', label, ...
    'Units', 'normalized', 'Position', [position(1), ...
    position(2)+position(4)+0.01, position(3), 0.09], ...
    'HorizontalAlignment', 'left');
control = uicontrol('Parent', parent, 'Style', 'edit', ...
    'String', value, 'Units', 'normalized', 'BackgroundColor', 'white', ...
    'Position', position);
end

function control = makeSignPopup(parent, labels, signValue, position)
value = 1;
if signValue < 0
    value = 2;
end
control = uicontrol('Parent', parent, 'Style', 'popupmenu', ...
    'String', labels, 'Value', value, 'Units', 'normalized', ...
    'Position', position, 'TooltipString', '信号/判据符号约定');
end

function handles = latestHandles(fig)
handles = get(fig, 'UserData');
end

function appendLog(fig, message)
handles = latestHandles(fig);
if ~isfield(handles, 'fdei') || ~ishandle(handles.fdei.batchUi.executionLogText)
    fprintf('[FDEI] %s\n', message);
    return;
end
control = handles.fdei.batchUi.executionLogText;
current = get(control, 'String');
if isempty(current)
    lines = {char(string(message))};
elseif ischar(current)
    lines = {current; char(string(message))};
else
    lines = [current; {char(string(message))}];
end
if numel(lines) > 100
    lines = lines(end-99:end);
end
set(control, 'String', lines, 'Value', numel(lines));
drawnow;
end

function setTableFromTable(control, value)
if isempty(value)
    set(control, 'Data', {});
    return;
end
set(control, 'Data', table2cell(value), 'ColumnName', value.Properties.VariableNames);
end

function value = joinNumbers(numbers)
value = strjoin(arrayfun(@(number) sprintf('%.8g', number), numbers, ...
    'UniformOutput', false), ', ');
end

function text = formatManualCases(cases)
if isempty(cases)
    text = '';
    return;
end
rows = compose('%.12g, %.12g', cases(:,1), cases(:,2));
text = char(strjoin(rows, '; '));
end

function value = iff(condition, trueValue, falseValue)
if condition
    value = trueValue;
else
    value = falseValue;
end
end
